bin/dev: Restart only if required

diff --git a/bin/cypress b/bin/cypress
--- a/bin/cypress
+++ b/bin/cypress
@@ -2,8 +2,14 @@
 
 # Use puma-dev in `development` environment (not `test` !) to run Cypress tests. This allows
 # editing the code while writing Cypress tests.
-grep -qxF 'CYPRESS=true' .env || echo 'CYPRESS=true' >> .env
-bin/rails restart
+if grep -q CYPRESS=true .env; then
+  echo "ok, .env already contains CYPRESS=true, no restart required"
+else
+  echo ".env does NOT contain CYPRESS=true, so add it and restart Rails"
+
+  grep -qxF 'CYPRESS=true' .env || echo 'CYPRESS=true' >> .env
+  touch tmp/restart.txt
+fi
 
 # Redirect arguments to cypress binary
 export CYPRESS_COMMANDS="$*"
